### ISSUE TITLE
Hook for Gulp in Sails.js ?

### ISSUE THREAD

**Issue by vincivince** [balderdashy/sails-generate-hook#1]
Hi,
im working on a`sails-generate-gulpfile`, and trying to merge ideas from `sails-generate-gulp-bower`, and your proposal here https://github.com/balderdashy/sails/issues/1461 .
At the end Sails.js need a hook to play with Gulp, no? 

To plug Gulp (tasks/hooks) in sails.js, do you plan something like :
- `sails-generate-gulp` (hook)
- `sails-generate-gulpfile`
- `sails-generate-gulpfrontend` (tasks + assets) ?

thx.

**Comment by davidchase** [comment]
@vdesbarres whats the status of the gulp generator?

**Comment by vincivince** [comment]
@davidchase I don't know right now, and i feel a bit confused with the approach and the actual generators functions. I think we need infos on `sails-generate-hook`. I also don't get the point in separating the grunt/gulpfile from their tasks folder, generated with the frontend generator...

**Comment by davidchase** [comment]
@vdesbarres I don't know about you but in order for gulp to really work without all of the grunt deps in the package.json  i had to modify sails-generate-new, sails-generate-frontend along with the sails-generate-gruntfile... IMO that might be too many modules to modify, but not 100% sure it's necessary

**Comment by vincivince** [comment]
@davidchase You're right its quite simple to fork and modify the actual grunt generators, frontend, to fit with gulp, browserify etc.. And finally, deactivate the hook for grunt in `.sailrc` file, while `sails lift`.

```
{
  "generators": {
    "modules": {}
 },
  "hooks": {
    "grunt": false
  }
}
```

We need options during `sails new` to override the default taskRunner. Again, we might modify the way hooks for taskrunner are implemented. maybe something like : 

```
{
  "generators": {
    "modules": {}
 },
  "hooks": {
    "taskrunner": "gulp"
  }
}
```

I agree also that it might represent a lot of modules to modify...

**Comment by Joker666** [comment]
+1 This needs more attention. A lot of us use Gulp

**Comment by mateeyow** [comment]
+1

**Comment by jmjpro** [comment]
+1

**Comment by theblang** [comment]
+1

**Comment by myrtleTree33** [comment]
+1

**Comment by perciag** [comment]
+1

**Comment by Karnith** [comment]
I have had generators for gulp for the last 11 months. See https://github.com/Karnith/sails-generate-new-gulp or the sails module page https://github.com/balderdashy/sails/blob/master/MODULES.md#generators. I have generators for bower and angular also. I haven't used grunt with sails for the last 11 months.

**Comment by ghost** [comment]
+1

**Comment by kis** [comment]
+1

**Comment by seth2810** [comment]
By the way of v. 0.11 i'll create sails-hook-gulp that's run gulpfile inside sails app directory https://www.npmjs.com/package/sails-hook-gulp

**Comment by Karnith** [comment]
I already have a user hook for sails and gulp, if you want to use that as an example.

**Comment by yf-hk** [comment]
Thanks @Karnith for your great work about gulp generators, I'm already using it. Also if sails swich to gulp, we can use gulp-inject instead of linker, it's way more flexible and powerful IMO. Also I used main-bower-files so that all the 3rd party bower files can be automatically included and injected to all pages. I find it pretty neat

**Comment by Karnith** [comment]
@andyhu I use main-bower-files also in a gulp task. I have a whole suite of generators from bower to gulp and even angular with or without additional web server.

**Comment by loicsaintroch** [comment]
I close this issue for several reasons:
- The Sails asset pipeline is very flexible. Whether you choose Grunt or Gulp or whatever you want, it will work. The Sails team decided to choose Grunt because it was the best tool when Sails was created.
- Don't forget Sails is a back-end framework and the front-end workflow is juste here for convenience.
- The new version of Sails allows you to load custom hook such as the Gulp hook directly from the `node_modules` directory. So, feel free to create custom hooks or generators.
- If we move from Grunt to Gulp, a lot of applications will be broken.

Then, as we can read on a presentation of the Grunt team about the state of Grunt:

> Grunt, Gulp, Broccoli, they're actually all good options. As long as you're using something, you're ahead of the game!

Thank you for your comprehension.

**Comment by yf-hk** [comment]
Thanks @loicsaintroch for your reply. I agree with you for the idea that it might not be a good thing to just `switch` to gulp, but instead what I would like to see is that sails will remove grunt as a hard dependency in the future, so if I choose gulp, it won't install any grunt modules any more. Or, in a better way, provide a generator option to support both js build system like MEAN.io.

**Comment by loicsaintroch** [comment]
Yes I agree with you. In my opinion Sails shouldn't take care of the front-end at all but it's pretty convenient for a lot of developers to have something running by default.

**Comment by Karnith** [comment]
@andyhu @loicsaintroch 

I'm in the process of integrating gulp into sails to allow grunt by default and gulp with a switch.

first round is working with just gulp, complete conversion from grunt

npm install -g Karnith/sails

Since I got it working, I'm going to start merging the two and add a switch in the "sails new" command....

**Comment by asemoon** [comment]
+1

**Comment by Karnith** [comment]
I've created a machinepack for this. Machinepack-sailsgulpify
